# Generated by Django 4.2.11 on 2024-04-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0002_alter_historicalanswer_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="post_owner",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="question",
            name="post_owner",
            field=models.IntegerField(default=0),
        ),
    ]
