# Generated by Django 4.2.11 on 2024-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0003_alter_historicalquestion_post_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="post_owner",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="question",
            name="post_owner",
            field=models.CharField(default="", max_length=100),
        ),
    ]
