# Generated by Django 4.2.11 on 2024-04-30 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("qa", "0005_alter_answer_answer_owner_alter_answer_questionans_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="questionans",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qa.question"
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="answer_owner",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="questionans",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="qa.question",
            ),
        ),
    ]
