# Generated by Django 4.2.11 on 2024-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0006_alter_answer_answer_owner_alter_answer_questionans_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="answer_owner",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="answer_owner",
            field=models.CharField(default="", max_length=100),
        ),
    ]
