# Generated by Django 4.2.11 on 2024-04-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0008_answer_answer_owner_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="question",
            field=models.IntegerField(default=0),
        ),
    ]
