# Generated by Django 4.2.12.dev20240419112930 on 2024-04-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0009_answer_question_historicalanswer_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="question",
            new_name="tmp",
        ),
        migrations.RenameField(
            model_name="historicalanswer",
            old_name="question",
            new_name="tmp",
        ),
    ]
