# Generated by Django 4.2.11 on 2024-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0010_rename_question_answer_tmp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentq",
            name="commented_by_username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="commentq",
            name="question_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalcommentq",
            name="commented_by_username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="historicalcommentq",
            name="question_id",
            field=models.IntegerField(default=0),
        ),
    ]
