# Generated by Django 4.2.11 on 2024-05-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("qa", "0011_commentq_commented_by_username_commentq_question_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="answer_owner_username",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="commentq",
            old_name="question_id",
            new_name="c_id",
        ),
        migrations.RenameField(
            model_name="commentq",
            old_name="commented_by_username",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="historicalanswer",
            old_name="answer_owner_username",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="historicalcommentq",
            old_name="question_id",
            new_name="c_id",
        ),
        migrations.RenameField(
            model_name="historicalcommentq",
            old_name="commented_by_username",
            new_name="username",
        ),
    ]
