# Generated by Django 4.2.11 on 2024-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="noti_receiver",
            field=models.CharField(default="", max_length=100),
        ),
    ]
