# Generated by Django 4.2.11 on 2024-04-30 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notification", "0003_alter_notification_noti_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="noti_receiver_username",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="notification",
            name="noti_receiver",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="noti_receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
